name: rl_env
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - brotli=1.1.0=hb547adb_1
  - brotli-bin=1.1.0=hb547adb_1
  - bzip2=1.0.8=h93a5062_5
  - ca-certificates=2024.2.2=hf0a4a13_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.1=pyhd8ed1ab_0
  - contourpy=1.2.0=py310hd137fd4_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.1=py310h692a8b6_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - farama-notifications=0.0.4=pyhd8ed1ab_0
  - fonttools=4.47.2=py310hd125d64_0
  - freetype=2.12.1=hadb7bae_2
  - gym=0.26.1=py310hbe9552e_0
  - gym-notices=0.0.8=pyhd8ed1ab_0
  - gymnasium=0.28.1=py310hc469350_0
  - importlib-metadata=7.0.1=pyha770c72_0
  - importlib_metadata=7.0.1=hd8ed1ab_0
  - ipykernel=6.29.3=pyh3cd1d5f_0
  - ipython=8.22.2=pyh707e725_0
  - jax-jumpy=1.0.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.7.1=py310hbe9552e_0
  - kiwisolver=1.4.5=py310h38f39d4_1
  - lcms2=2.16=ha0e7c42_0
  - lerc=4.0.0=h9a09cb3_0
  - libblas=3.9.0=20_osxarm64_openblas
  - libbrotlicommon=1.1.0=hb547adb_1
  - libbrotlidec=1.1.0=hb547adb_1
  - libbrotlienc=1.1.0=hb547adb_1
  - libcblas=3.9.0=20_osxarm64_openblas
  - libcxx=16.0.6=h4653b0c_0
  - libdeflate=1.19=hb547adb_0
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=13_2_0_hd922786_1
  - libgfortran5=13.2.0=hf226fd6_1
  - libjpeg-turbo=3.0.0=hb547adb_1
  - liblapack=3.9.0=20_osxarm64_openblas
  - libopenblas=0.3.25=openmp_h6c19121_0
  - libpng=1.6.39=h76d750c_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.44.2=h091b4b1_0
  - libtiff=4.6.0=ha8a6c65_2
  - libwebp-base=1.3.2=hb547adb_0
  - libxcb=1.15=hf346824_0
  - libzlib=1.2.13=h53f4e23_5
  - llvm-openmp=17.0.6=hcd81f8e_0
  - matplotlib=3.8.2=py310hb6292c7_0
  - matplotlib-base=3.8.2=py310h9d2df84_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=h463b476_2
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - numpy=1.26.3=py310hd45542a_0
  - openjpeg=2.5.0=h4c1507b_3
  - openssl=3.2.1=h0d3ecfb_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.2.0=py310h401b61c_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.2.0=py310hfae7ebd_0
  - pip=23.3.2=pyhd8ed1ab_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.8=py310hd125d64_0
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - python=3.10.13=h2469fbe_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.4=pyhd8ed1ab_0
  - python_abi=3.10=4_cp310
  - pytz=2023.4=pyhd8ed1ab_0
  - pyzmq=25.1.2=py310hbb13138_0
  - readline=8.2=h92ec313_1
  - scipy=1.12.0=py310hf4b343e_2
  - setuptools=69.0.3=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - tornado=6.3.3=py310h2aa6e3c_1
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.14.1=pyhd8ed1ab_0
  - typing_extensions=4.9.0=pyha770c72_0
  - tzdata=2023d=h0c530f3_0
  - unicodedata2=15.1.0=py310h2aa6e3c_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xz=5.2.6=h57fd34a_0
  - zeromq=4.3.5=hebf3989_1
  - zipp=3.17.0=pyhd8ed1ab_0
  - zstd=1.5.5=h4f39d0f_0
prefix: /Users/dimavremenko/miniconda3/envs/rl_env
